### ISSUE TITLE
Can't move past an apostrophe

### ISSUE THREAD

**Issue by benallred** [nvlgzr/fngrng#7]
![image](https://user-images.githubusercontent.com/3902274/155355108-de264996-7522-46a1-af2b-9ca19d512907.png)

## System Details
 - OS: Windows 11
 - Browser: Edge Dev

**Comment by nvlgzr** [comment]
Yikes! That's not good. Thanks for reporting, @benallred!

I'm not quite sure what's happening. The only clue so far is that your prompt is showing a typographic apostrophe `’,` whereas mine's using a typewriter apostrophe `'`.

<img width="606" alt="Screenshot demonstrating apostrophes in fngrng on my Mac" src="https://user-images.githubusercontent.com/88254481/155794622-6d1aaa2a-10c1-4f13-8b5d-6c46a2cc834c.png">

I'm curious, do you run into the same issue on https://colemak.academy?

**Comment by benallred** [comment]
It's taken me quite a while to get far enough into the full sentence mode there to find at least a double-quote and that seems to be working.

![image](https://user-images.githubusercontent.com/3902274/155799205-583c25ed-cd08-42c9-86ed-e7fe824ac445.png)

**Comment by benallred** [comment]
I'm silly. I turned on punctuation and tried again. It is working:

![image](https://user-images.githubusercontent.com/3902274/155799406-9acf9c7a-b4df-4e3f-a9cb-691cbaf42970.png)

**Comment by nvlgzr** [comment]
The good news is, you're not crazy or even (that I know of) silly: you found a legit bug!

I suspect you were typing out the James Baldwin quote, which has not one, but two typographical quotes in it. Should be fixed in a few minutes.

Anyway, congratulations, @benallred! You seem to have made it further into that passage than I ever did. 😁
